package view;

import efeitos.EfeitoMenu;
import efeitos.ExpandirMenu;
import extencaoBiblioteca.CustomScrolBarUI;
import java.awt.Color;
import java.awt.Dimension;
import java.util.logging.Level;
import java.util.logging.Logger;

public class MenuView extends javax.swing.JFrame {

    /**
     * Creates new form MenuView
     */
    final int XMENU = 410;
    private EfeitoMenu efeito;

    public MenuView() {

        initComponents();

        efeito = new EfeitoMenu();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuJPanel = new javax.swing.JPanel();
        menuItemJPanel = new javax.swing.JPanel();
        painelMenuItemJPanel = new javax.swing.JPanel();
        scrollMenuItemJScrollPane = new javax.swing.JScrollPane();
        painelScrollMenuItemJScrollPane = new javax.swing.JPanel();
        painelVendasJPanel = new javax.swing.JPanel();
        painelExpansivoVendasJPanel = new javax.swing.JPanel();
        vendasTextoJLabel = new javax.swing.JLabel();
        vendasLinhaJLabel = new javax.swing.JLabel();
        indicadorVendasJPanel = new javax.swing.JPanel();
        indicadorVendasJLabel = new javax.swing.JLabel();
        painelBalcaoJPanel = new javax.swing.JPanel();
        textoBalcaoJLabel = new javax.swing.JLabel();
        iconeBalcao = new javax.swing.JLabel();
        backgroundBalcaoJLabel = new javax.swing.JLabel();
        painelComandaJPanel = new javax.swing.JPanel();
        textoComandaJLabel = new javax.swing.JLabel();
        iconeComanda = new javax.swing.JLabel();
        backgroundComandaJLabel = new javax.swing.JLabel();
        painelMapaComandaJPanel = new javax.swing.JPanel();
        textoMapaComandaJLabel = new javax.swing.JLabel();
        iconeMapaComanda = new javax.swing.JLabel();
        backgroundMapaComandaJLabel = new javax.swing.JLabel();
        painelCaixaJPanel = new javax.swing.JPanel();
        painelExpansivoCaixaItemJPanel = new javax.swing.JPanel();
        caixaTextoJLabel = new javax.swing.JLabel();
        caixaLinhaJLabel = new javax.swing.JLabel();
        indicadorCaixaItemJPanel = new javax.swing.JPanel();
        indicadorCaixaItemJLabel = new javax.swing.JLabel();
        painelCaixaAbrirFecharJPanel = new javax.swing.JPanel();
        iconeCaixaAbrirFecharJLabel = new javax.swing.JLabel();
        textoCaixaAbrirFecharJLabel = new javax.swing.JLabel();
        backgroundCaixaJLabel = new javax.swing.JLabel();
        painelRelatorioCaixaJPanel = new javax.swing.JPanel();
        iconeRelatorioCaixa = new javax.swing.JLabel();
        textoRelatorioCaixaJLabel = new javax.swing.JLabel();
        backgroundRelatorioCaixaJLabel = new javax.swing.JLabel();
        painelReceberContasJPanel = new javax.swing.JPanel();
        textoReceberContaJLabel = new javax.swing.JLabel();
        iconeReceberConta = new javax.swing.JLabel();
        backgroundReceberContasJLabel = new javax.swing.JLabel();
        painelContasPagarJPanel = new javax.swing.JPanel();
        painelExpansivoContasPagarJPanel = new javax.swing.JPanel();
        contasTextoJLabel = new javax.swing.JLabel();
        contasLinhaJLabel = new javax.swing.JLabel();
        indicadorContasPagarJPanel = new javax.swing.JPanel();
        indicadorContasPagarJLabel = new javax.swing.JLabel();
        painelBuscarContaJPanel = new javax.swing.JPanel();
        iconeBuscarContaJLabel = new javax.swing.JLabel();
        textoBuscarContaLabel = new javax.swing.JLabel();
        backgroundBuscarContaJLabel = new javax.swing.JLabel();
        painelAddContaJPanel = new javax.swing.JPanel();
        iconeAddConta = new javax.swing.JLabel();
        textoAddContaJLabel = new javax.swing.JLabel();
        backgroundAddContaJLabel = new javax.swing.JLabel();
        painelFuncionarioJPanel = new javax.swing.JPanel();
        painelExpansivoFuncionarioJPanel = new javax.swing.JPanel();
        funcionarioTextoJLabel = new javax.swing.JLabel();
        funcionarioLinhaJLabel = new javax.swing.JLabel();
        indicadorFuncionarioJPanel = new javax.swing.JPanel();
        indicadorFuncionarioJLabel = new javax.swing.JLabel();
        painelBuscarFuncionarioJPanel = new javax.swing.JPanel();
        iconeBuscarFuncionarioJLabel = new javax.swing.JLabel();
        textoBuscarFuncionarioLabel = new javax.swing.JLabel();
        backgroundBuscarFuncionarioJLabel = new javax.swing.JLabel();
        painelAddFuncionarioJPanel = new javax.swing.JPanel();
        iconeAddFuncionario = new javax.swing.JLabel();
        textoAddFuncionarioJLabel = new javax.swing.JLabel();
        backgroundAddFuncionarioJLabel = new javax.swing.JLabel();
        menuItemJlabel = new javax.swing.JLabel();
        menuJLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MenuJFrame");
        setMaximumSize(new java.awt.Dimension(1980, 1080));
        setName("MenuJFrame"); // NOI18N
        setUndecorated(true);

        menuJPanel.setMaximumSize(getMaximumSize());
        menuJPanel.setMinimumSize(getMinimumSize());
        menuJPanel.setName(""); // NOI18N
        menuJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuItemJPanel.setAlignmentX(0.0F);
        menuItemJPanel.setAlignmentY(0.0F);
        menuItemJPanel.setMaximumSize(new java.awt.Dimension(422, 668));
        menuItemJPanel.setName(""); // NOI18N
        menuItemJPanel.setOpaque(false);
        menuItemJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        painelMenuItemJPanel.setOpaque(false);
        painelMenuItemJPanel.setLayout(null);
        painelMenuItemJPanel.setSize(382, 425);

        scrollMenuItemJScrollPane.setBackground(new Color(0,0,0,0));

        scrollMenuItemJScrollPane.setViewportBorder(null);

        scrollMenuItemJScrollPane.getVerticalScrollBar().setUI(new CustomScrolBarUI());
        scrollMenuItemJScrollPane.setOpaque(false);
        scrollMenuItemJScrollPane.getViewport().setOpaque(false);
        scrollMenuItemJScrollPane.setBorder(null);
        scrollMenuItemJScrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollMenuItemJScrollPane.setAlignmentX(0.0F);
        scrollMenuItemJScrollPane.setAlignmentY(0.0F);
        scrollMenuItemJScrollPane.setMaximumSize(new java.awt.Dimension(410, 425));
        scrollMenuItemJScrollPane.setMinimumSize(new java.awt.Dimension(410, 425));
        scrollMenuItemJScrollPane.setPreferredSize(new java.awt.Dimension(382, 425));

        painelScrollMenuItemJScrollPane.setOpaque(false);
        painelScrollMenuItemJScrollPane.setPreferredSize(new java.awt.Dimension(410, 425));
        painelScrollMenuItemJScrollPane.setLayout(null);
        painelScrollMenuItemJScrollPane.setBounds(0, 0, XMENU, 425);

        painelVendasJPanel.setOpaque(false);
        painelVendasJPanel.setLayout(null);

        painelExpansivoVendasJPanel.setMinimumSize(new java.awt.Dimension(380, 20));
        painelExpansivoVendasJPanel.setOpaque(false);
        painelExpansivoVendasJPanel.setPreferredSize(new java.awt.Dimension(380, 20));
        painelExpansivoVendasJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        vendasTextoJLabel.setFont(new java.awt.Font("Futura Bk BT", 0, 18)); // NOI18N
        vendasTextoJLabel.setForeground(new java.awt.Color(255, 255, 255));
        vendasTextoJLabel.setLabelFor(painelExpansivoVendasJPanel);
        vendasTextoJLabel.setText("Vendas");
        vendasTextoJLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        vendasTextoJLabel.setNextFocusableComponent(painelExpansivoVendasJPanel);
        vendasTextoJLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vendasTextoJLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                vendasTextoJLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                vendasTextoJLabelMouseExited(evt);
            }
        });
        painelExpansivoVendasJPanel.add(vendasTextoJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 27));

        vendasLinhaJLabel.setForeground(new java.awt.Color(255, 255, 255));
        vendasLinhaJLabel.setText("______________________________________________________");
        vendasLinhaJLabel.setToolTipText("");
        vendasLinhaJLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        vendasLinhaJLabel.setFocusable(false);
        vendasLinhaJLabel.setRequestFocusEnabled(false);
        vendasLinhaJLabel.setVerifyInputWhenFocusTarget(false);
        painelExpansivoVendasJPanel.add(vendasLinhaJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 8, 400, 16));

        indicadorVendasJPanel.setOpaque(false);
        indicadorVendasJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        indicadorVendasJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/SetaFechado.png"))); // NOI18N
        indicadorVendasJPanel.add(indicadorVendasJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 15, 15));

        painelExpansivoVendasJPanel.add(indicadorVendasJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 1, 15, 15));

        painelVendasJPanel.add(painelExpansivoVendasJPanel);
        painelExpansivoVendasJPanel.setBounds(0, 0, 400, 27);

        painelBalcaoJPanel.setAlignmentX(0.0F);
        painelBalcaoJPanel.setAlignmentY(0.0F);
        painelBalcaoJPanel.setOpaque(false);
        painelBalcaoJPanel.setVisible(false);
        painelBalcaoJPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                painelBalcaoJPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                painelBalcaoJPanelMouseExited(evt);
            }
        });
        painelBalcaoJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textoBalcaoJLabel.setFont(new java.awt.Font("Futura Bk BT", 0, 24)); // NOI18N
        textoBalcaoJLabel.setText("Balcão");
        textoBalcaoJLabel.setAlignmentY(0.0F);
        painelBalcaoJPanel.add(textoBalcaoJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 7, 261, 26));

        iconeBalcao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/IconeBalcao.png"))); // NOI18N
        painelBalcaoJPanel.add(iconeBalcao, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 0, 40, -1));

        backgroundBalcaoJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/BackgroundItensMenu.png"))); // NOI18N
        painelBalcaoJPanel.add(backgroundBalcaoJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, -1));

        painelVendasJPanel.add(painelBalcaoJPanel);
        painelBalcaoJPanel.setBounds(0, 27, 382, 50);

        painelComandaJPanel.setBackground(new java.awt.Color(102, 255, 153));
        painelComandaJPanel.setOpaque(false);
        painelComandaJPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                painelComandaJPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                painelComandaJPanelMouseExited(evt);
            }
        });
        painelComandaJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        painelComandaJPanel.setVisible(false);

        textoComandaJLabel.setFont(new java.awt.Font("Futura Bk BT", 0, 24)); // NOI18N
        textoComandaJLabel.setText("Comanda");
        textoComandaJLabel.setToolTipText("");
        textoComandaJLabel.setAlignmentY(0.0F);
        painelComandaJPanel.add(textoComandaJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 7, 261, 26));

        iconeComanda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/IconeComanda.png"))); // NOI18N
        painelComandaJPanel.add(iconeComanda, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 0, 40, 43));

        backgroundComandaJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/BackgroundItensMenu.png"))); // NOI18N
        painelComandaJPanel.add(backgroundComandaJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 43));

        painelVendasJPanel.add(painelComandaJPanel);
        painelComandaJPanel.setBounds(0, 77, 382, 50);

        painelMapaComandaJPanel.setBackground(new java.awt.Color(153, 255, 153));
        painelMapaComandaJPanel.setOpaque(false);
        painelMapaComandaJPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                painelMapaComandaJPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                painelMapaComandaJPanelMouseExited(evt);
            }
        });
        painelMapaComandaJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        painelMapaComandaJPanel.setVisible(false);

        textoMapaComandaJLabel.setFont(new java.awt.Font("Futura Bk BT", 0, 24)); // NOI18N
        textoMapaComandaJLabel.setText("Mapa de Comandas");
        textoMapaComandaJLabel.setAlignmentY(0.0F);
        painelMapaComandaJPanel.add(textoMapaComandaJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 7, 261, 26));

        iconeMapaComanda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/IconeMapaComanda.png"))); // NOI18N
        iconeMapaComanda.setToolTipText("");
        painelMapaComandaJPanel.add(iconeMapaComanda, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 0, 40, 43));

        backgroundMapaComandaJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/BackgroundItensMenu.png"))); // NOI18N
        backgroundMapaComandaJLabel.setAlignmentY(0.0F);
        painelMapaComandaJPanel.add(backgroundMapaComandaJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 43));

        painelVendasJPanel.add(painelMapaComandaJPanel);
        painelMapaComandaJPanel.setBounds(0, 127, 382, 53);

        painelScrollMenuItemJScrollPane.add(painelVendasJPanel);
        painelVendasJPanel.setBounds(0, 0, 382, 177);
        painelVendasJPanel.setBounds(0, 0, 382, 27);

        painelCaixaJPanel.setMinimumSize(new java.awt.Dimension(380, 160));
        painelCaixaJPanel.setOpaque(false);
        painelCaixaJPanel.setPreferredSize(new java.awt.Dimension(380, 155));
        painelCaixaJPanel.setLayout(null);

        painelExpansivoCaixaItemJPanel.setOpaque(false);
        painelExpansivoCaixaItemJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        caixaTextoJLabel.setFont(new java.awt.Font("Futura Bk BT", 0, 18)); // NOI18N
        caixaTextoJLabel.setForeground(new java.awt.Color(255, 255, 255));
        caixaTextoJLabel.setLabelFor(painelExpansivoVendasJPanel);
        caixaTextoJLabel.setText("Caixa");
        caixaTextoJLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        caixaTextoJLabel.setNextFocusableComponent(painelExpansivoVendasJPanel);
        caixaTextoJLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                caixaTextoJLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                caixaTextoJLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                caixaTextoJLabelMouseExited(evt);
            }
        });
        painelExpansivoCaixaItemJPanel.add(caixaTextoJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 27));

        caixaLinhaJLabel.setForeground(new java.awt.Color(255, 255, 255));
        caixaLinhaJLabel.setText("______________________________________________________");
        caixaLinhaJLabel.setToolTipText("");
        caixaLinhaJLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        caixaLinhaJLabel.setFocusable(false);
        caixaLinhaJLabel.setRequestFocusEnabled(false);
        caixaLinhaJLabel.setVerifyInputWhenFocusTarget(false);
        painelExpansivoCaixaItemJPanel.add(caixaLinhaJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 8, 400, 16));

        indicadorCaixaItemJPanel.setOpaque(false);
        indicadorCaixaItemJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        indicadorCaixaItemJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/SetaFechado.png"))); // NOI18N
        indicadorCaixaItemJPanel.add(indicadorCaixaItemJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 15, 15));

        painelExpansivoCaixaItemJPanel.add(indicadorCaixaItemJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 1, 15, 15));

        painelCaixaJPanel.add(painelExpansivoCaixaItemJPanel);
        painelExpansivoCaixaItemJPanel.setBounds(0, 0, 400, 27);

        painelCaixaAbrirFecharJPanel.setOpaque(false);
        painelCaixaAbrirFecharJPanel.setVisible(false);
        painelCaixaAbrirFecharJPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                painelCaixaAbrirFecharJPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                painelCaixaAbrirFecharJPanelMouseExited(evt);
            }
        });
        painelCaixaAbrirFecharJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconeCaixaAbrirFecharJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/IconeRegistradora.png"))); // NOI18N
        painelCaixaAbrirFecharJPanel.add(iconeCaixaAbrirFecharJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 0, 40, 40));

        textoCaixaAbrirFecharJLabel.setFont(new java.awt.Font("Futura Bk BT", 0, 24)); // NOI18N
        textoCaixaAbrirFecharJLabel.setText("Abrir Caixa");
        textoCaixaAbrirFecharJLabel.setAlignmentY(0.0F);
        painelCaixaAbrirFecharJPanel.add(textoCaixaAbrirFecharJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 7, 261, 26));

        backgroundCaixaJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/BackgroundItensMenu.png"))); // NOI18N
        painelCaixaAbrirFecharJPanel.add(backgroundCaixaJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 382, 43));

        painelCaixaJPanel.add(painelCaixaAbrirFecharJPanel);
        painelCaixaAbrirFecharJPanel.setBounds(0, 27, 382, 50);

        painelRelatorioCaixaJPanel.setBackground(new java.awt.Color(102, 255, 153));
        painelRelatorioCaixaJPanel.setOpaque(false);
        painelRelatorioCaixaJPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                painelRelatorioCaixaJPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                painelRelatorioCaixaJPanelMouseExited(evt);
            }
        });
        painelRelatorioCaixaJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        painelRelatorioCaixaJPanel.setVisible(false);

        iconeRelatorioCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/IconeRelatorioCaixa.png"))); // NOI18N
        iconeRelatorioCaixa.setToolTipText("");
        painelRelatorioCaixaJPanel.add(iconeRelatorioCaixa, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 0, 42, 43));

        textoRelatorioCaixaJLabel.setFont(new java.awt.Font("Futura Bk BT", 0, 24)); // NOI18N
        textoRelatorioCaixaJLabel.setText("Relatorio Caixa");
        textoRelatorioCaixaJLabel.setAlignmentY(0.0F);
        painelRelatorioCaixaJPanel.add(textoRelatorioCaixaJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 7, 261, 26));

        backgroundRelatorioCaixaJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/BackgroundItensMenu.png"))); // NOI18N
        painelRelatorioCaixaJPanel.add(backgroundRelatorioCaixaJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 382, 43));

        painelCaixaJPanel.add(painelRelatorioCaixaJPanel);
        painelRelatorioCaixaJPanel.setBounds(0, 77, 382, 50);

        painelReceberContasJPanel.setBackground(new java.awt.Color(153, 255, 153));
        painelReceberContasJPanel.setOpaque(false);
        painelReceberContasJPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                painelReceberContasJPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                painelReceberContasJPanelMouseExited(evt);
            }
        });
        painelReceberContasJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        painelReceberContasJPanel.setVisible(false);

        textoReceberContaJLabel.setFont(new java.awt.Font("Futura Bk BT", 0, 24)); // NOI18N
        textoReceberContaJLabel.setText("Receber Contas");
        textoReceberContaJLabel.setAlignmentY(0.0F);
        painelReceberContasJPanel.add(textoReceberContaJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 7, 261, 26));

        iconeReceberConta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/IconeReceberContas.png"))); // NOI18N
        iconeReceberConta.setToolTipText("");
        painelReceberContasJPanel.add(iconeReceberConta, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 0, 42, 43));

        backgroundReceberContasJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/BackgroundItensMenu.png"))); // NOI18N
        painelReceberContasJPanel.add(backgroundReceberContasJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 382, 43));

        painelCaixaJPanel.add(painelReceberContasJPanel);
        painelReceberContasJPanel.setBounds(0, 127, 382, 50);

        painelScrollMenuItemJScrollPane.add(painelCaixaJPanel);
        painelCaixaJPanel.setBounds(0, 177, 382, 177);
        painelCaixaJPanel.setBounds(0, 27, 382, 27);

        painelContasPagarJPanel.setMinimumSize(new java.awt.Dimension(380, 160));
        painelContasPagarJPanel.setOpaque(false);
        painelContasPagarJPanel.setPreferredSize(new java.awt.Dimension(380, 155));
        painelContasPagarJPanel.setLayout(null);

        painelExpansivoContasPagarJPanel.setOpaque(false);
        painelExpansivoContasPagarJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contasTextoJLabel.setFont(new java.awt.Font("Futura Bk BT", 0, 18)); // NOI18N
        contasTextoJLabel.setForeground(new java.awt.Color(255, 255, 255));
        contasTextoJLabel.setLabelFor(painelExpansivoVendasJPanel);
        contasTextoJLabel.setText("Receber Contas");
        contasTextoJLabel.setToolTipText("");
        contasTextoJLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        contasTextoJLabel.setNextFocusableComponent(painelExpansivoVendasJPanel);
        contasTextoJLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contasTextoJLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                contasTextoJLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                contasTextoJLabelMouseExited(evt);
            }
        });
        painelExpansivoContasPagarJPanel.add(contasTextoJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 27));

        contasLinhaJLabel.setForeground(new java.awt.Color(255, 255, 255));
        contasLinhaJLabel.setText("______________________________________________________");
        contasLinhaJLabel.setToolTipText("");
        contasLinhaJLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        contasLinhaJLabel.setFocusable(false);
        contasLinhaJLabel.setRequestFocusEnabled(false);
        contasLinhaJLabel.setVerifyInputWhenFocusTarget(false);
        painelExpansivoContasPagarJPanel.add(contasLinhaJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 8, 400, 16));

        indicadorContasPagarJPanel.setOpaque(false);
        indicadorContasPagarJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        indicadorContasPagarJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/SetaFechado.png"))); // NOI18N
        indicadorContasPagarJPanel.add(indicadorContasPagarJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 15, 15));

        painelExpansivoContasPagarJPanel.add(indicadorContasPagarJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 1, 15, 15));

        painelContasPagarJPanel.add(painelExpansivoContasPagarJPanel);
        painelExpansivoContasPagarJPanel.setBounds(0, 0, 382, 27);

        painelBuscarContaJPanel.setOpaque(false);
        painelBuscarContaJPanel.setVisible(false);
        painelBuscarContaJPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                painelBuscarContaJPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                painelBuscarContaJPanelMouseExited(evt);
            }
        });
        painelBuscarContaJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconeBuscarContaJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/IconeRegistradora.png"))); // NOI18N
        painelBuscarContaJPanel.add(iconeBuscarContaJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 0, 40, 40));

        textoBuscarContaLabel.setFont(new java.awt.Font("Futura Bk BT", 0, 24)); // NOI18N
        textoBuscarContaLabel.setText("Buscar Cliente");
        textoBuscarContaLabel.setAlignmentY(0.0F);
        painelBuscarContaJPanel.add(textoBuscarContaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 7, 261, 26));

        backgroundBuscarContaJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/BackgroundItensMenu.png"))); // NOI18N
        painelBuscarContaJPanel.add(backgroundBuscarContaJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 382, 43));

        painelContasPagarJPanel.add(painelBuscarContaJPanel);
        painelBuscarContaJPanel.setBounds(0, 27, 382, 50);

        painelAddContaJPanel.setBackground(new java.awt.Color(102, 255, 153));
        painelAddContaJPanel.setOpaque(false);
        painelAddContaJPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                painelAddContaJPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                painelAddContaJPanelMouseExited(evt);
            }
        });
        painelAddContaJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        painelAddContaJPanel.setVisible(false);

        iconeAddConta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/IconeRelatorioCaixa.png"))); // NOI18N
        iconeAddConta.setToolTipText("");
        painelAddContaJPanel.add(iconeAddConta, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 0, 42, 43));

        textoAddContaJLabel.setFont(new java.awt.Font("Futura Bk BT", 0, 24)); // NOI18N
        textoAddContaJLabel.setText("Cadastrar Cliente");
        textoAddContaJLabel.setAlignmentY(0.0F);
        painelAddContaJPanel.add(textoAddContaJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 7, 261, 26));

        backgroundAddContaJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/BackgroundItensMenu.png"))); // NOI18N
        painelAddContaJPanel.add(backgroundAddContaJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 382, 43));

        painelContasPagarJPanel.add(painelAddContaJPanel);
        painelAddContaJPanel.setBounds(0, 77, 382, 50);

        painelScrollMenuItemJScrollPane.add(painelContasPagarJPanel);
        painelContasPagarJPanel.setBounds(0, 355, 382, 127);
        painelContasPagarJPanel.setBounds(0, 54, 382, 27);

        painelFuncionarioJPanel.setMinimumSize(new java.awt.Dimension(380, 160));
        painelFuncionarioJPanel.setOpaque(false);
        painelFuncionarioJPanel.setPreferredSize(new java.awt.Dimension(380, 155));
        painelFuncionarioJPanel.setLayout(null);

        painelExpansivoFuncionarioJPanel.setOpaque(false);
        painelExpansivoFuncionarioJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        funcionarioTextoJLabel.setFont(new java.awt.Font("Futura Bk BT", 0, 18)); // NOI18N
        funcionarioTextoJLabel.setForeground(new java.awt.Color(255, 255, 255));
        funcionarioTextoJLabel.setLabelFor(painelExpansivoVendasJPanel);
        funcionarioTextoJLabel.setText("Funcionario");
        funcionarioTextoJLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        funcionarioTextoJLabel.setNextFocusableComponent(painelExpansivoVendasJPanel);
        funcionarioTextoJLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                funcionarioTextoJLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                funcionarioTextoJLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                funcionarioTextoJLabelMouseExited(evt);
            }
        });
        painelExpansivoFuncionarioJPanel.add(funcionarioTextoJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 27));

        funcionarioLinhaJLabel.setForeground(new java.awt.Color(255, 255, 255));
        funcionarioLinhaJLabel.setText("______________________________________________________");
        funcionarioLinhaJLabel.setToolTipText("");
        funcionarioLinhaJLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        funcionarioLinhaJLabel.setFocusable(false);
        funcionarioLinhaJLabel.setRequestFocusEnabled(false);
        funcionarioLinhaJLabel.setVerifyInputWhenFocusTarget(false);
        painelExpansivoFuncionarioJPanel.add(funcionarioLinhaJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 8, 400, 16));

        indicadorFuncionarioJPanel.setOpaque(false);
        indicadorFuncionarioJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        indicadorFuncionarioJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/SetaFechado.png"))); // NOI18N
        indicadorFuncionarioJPanel.add(indicadorFuncionarioJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 15, 15));

        painelExpansivoFuncionarioJPanel.add(indicadorFuncionarioJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 1, 15, 15));

        painelFuncionarioJPanel.add(painelExpansivoFuncionarioJPanel);
        painelExpansivoFuncionarioJPanel.setBounds(0, 0, 382, 27);

        painelBuscarFuncionarioJPanel.setOpaque(false);
        painelBuscarFuncionarioJPanel.setVisible(false);
        painelBuscarFuncionarioJPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                painelBuscarFuncionarioJPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                painelBuscarFuncionarioJPanelMouseExited(evt);
            }
        });
        painelBuscarFuncionarioJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconeBuscarFuncionarioJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/IconeRegistradora.png"))); // NOI18N
        painelBuscarFuncionarioJPanel.add(iconeBuscarFuncionarioJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 0, 40, 40));

        textoBuscarFuncionarioLabel.setFont(new java.awt.Font("Futura Bk BT", 0, 24)); // NOI18N
        textoBuscarFuncionarioLabel.setText("Buscar Funcionario");
        textoBuscarFuncionarioLabel.setAlignmentY(0.0F);
        painelBuscarFuncionarioJPanel.add(textoBuscarFuncionarioLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 7, 261, 26));

        backgroundBuscarFuncionarioJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/BackgroundItensMenu.png"))); // NOI18N
        painelBuscarFuncionarioJPanel.add(backgroundBuscarFuncionarioJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 382, 43));

        painelFuncionarioJPanel.add(painelBuscarFuncionarioJPanel);
        painelBuscarFuncionarioJPanel.setBounds(0, 27, 382, 50);

        painelAddFuncionarioJPanel.setBackground(new java.awt.Color(102, 255, 153));
        painelAddFuncionarioJPanel.setOpaque(false);
        painelAddFuncionarioJPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                painelAddFuncionarioJPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                painelAddFuncionarioJPanelMouseExited(evt);
            }
        });
        painelAddFuncionarioJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        painelAddFuncionarioJPanel.setVisible(false);

        iconeAddFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/IconeRelatorioCaixa.png"))); // NOI18N
        iconeAddFuncionario.setToolTipText("");
        painelAddFuncionarioJPanel.add(iconeAddFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 0, 42, 43));

        textoAddFuncionarioJLabel.setFont(new java.awt.Font("Futura Bk BT", 0, 24)); // NOI18N
        textoAddFuncionarioJLabel.setText("Cadastrar Cliente");
        textoAddFuncionarioJLabel.setAlignmentY(0.0F);
        painelAddFuncionarioJPanel.add(textoAddFuncionarioJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 7, 261, 26));

        backgroundAddFuncionarioJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/BackgroundItensMenu.png"))); // NOI18N
        painelAddFuncionarioJPanel.add(backgroundAddFuncionarioJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 382, 43));

        painelFuncionarioJPanel.add(painelAddFuncionarioJPanel);
        painelAddFuncionarioJPanel.setBounds(0, 77, 382, 50);

        painelScrollMenuItemJScrollPane.add(painelFuncionarioJPanel);
        painelFuncionarioJPanel.setBounds(0, 482, 382, 127);
        painelFuncionarioJPanel.setBounds(0, 81, 382, 27);

        scrollMenuItemJScrollPane.setViewportView(painelScrollMenuItemJScrollPane);

        painelMenuItemJPanel.add(scrollMenuItemJScrollPane);
        scrollMenuItemJScrollPane.setBounds(0, 0, 400, 425);

        menuItemJPanel.add(painelMenuItemJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 230, 410, 425));

        menuItemJlabel.setBackground(new java.awt.Color(102, 255, 102));
        menuItemJlabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        menuItemJlabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/BackgroundMenuItem.png"))); // NOI18N
        menuItemJlabel.setToolTipText("");
        menuItemJlabel.setAlignmentY(0.0F);
        menuItemJlabel.setMinimumSize(new java.awt.Dimension(0, 0));
        menuItemJPanel.add(menuItemJlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 422, 668));

        menuJPanel.add(menuItemJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 26, -1, -1));

        menuJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/BackgroundMenu.png"))); // NOI18N
        menuJLabel.setToolTipText("");
        menuJLabel.setMaximumSize(getMaximumSize());
        menuJLabel.setMinimumSize(getMinimumSize());
        menuJPanel.add(menuJLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //EFEITO NOS ITENS DO MENU VENDAS
    private void painelBalcaoJPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelBalcaoJPanelMouseEntered
        try {
            efeito.EfeitoIcone(backgroundBalcaoJLabel, painelBalcaoJPanel);
        } catch (InterruptedException ex) {
            Logger.getLogger(MenuView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_painelBalcaoJPanelMouseEntered

    private void painelBalcaoJPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelBalcaoJPanelMouseExited
        try {
            efeito.EfeitoIcone(backgroundBalcaoJLabel, painelBalcaoJPanel);
        } catch (InterruptedException ex) {
            Logger.getLogger(MenuView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_painelBalcaoJPanelMouseExited

    private void painelComandaJPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelComandaJPanelMouseEntered
        try {
            efeito.EfeitoIcone(backgroundComandaJLabel, painelComandaJPanel);
        } catch (InterruptedException ex) {
            Logger.getLogger(MenuView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_painelComandaJPanelMouseEntered

    private void painelComandaJPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelComandaJPanelMouseExited
        try {
            efeito.EfeitoIcone(backgroundComandaJLabel, painelComandaJPanel);
        } catch (InterruptedException ex) {
            Logger.getLogger(MenuView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_painelComandaJPanelMouseExited

    private void painelMapaComandaJPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelMapaComandaJPanelMouseEntered
        try {
            efeito.EfeitoIcone(backgroundMapaComandaJLabel, painelMapaComandaJPanel);
        } catch (InterruptedException ex) {
            Logger.getLogger(MenuView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_painelMapaComandaJPanelMouseEntered

    private void painelMapaComandaJPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelMapaComandaJPanelMouseExited
        try {
            efeito.EfeitoIcone(backgroundMapaComandaJLabel, painelMapaComandaJPanel);
        } catch (InterruptedException ex) {
            Logger.getLogger(MenuView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_painelMapaComandaJPanelMouseExited

    //EFEITO NOS ITENS DO MENU CAIXA
    private void painelCaixaAbrirFecharJPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelCaixaAbrirFecharJPanelMouseEntered
        try {
            efeito.EfeitoIcone(backgroundCaixaJLabel, painelCaixaAbrirFecharJPanel);
        } catch (InterruptedException ex) {
            Logger.getLogger(MenuView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_painelCaixaAbrirFecharJPanelMouseEntered

    private void painelCaixaAbrirFecharJPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelCaixaAbrirFecharJPanelMouseExited
        try {
            efeito.EfeitoIcone(backgroundCaixaJLabel, painelCaixaAbrirFecharJPanel);
        } catch (InterruptedException ex) {
            Logger.getLogger(MenuView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_painelCaixaAbrirFecharJPanelMouseExited

    private void painelRelatorioCaixaJPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelRelatorioCaixaJPanelMouseEntered
        try {
            efeito.EfeitoIcone(backgroundRelatorioCaixaJLabel, painelRelatorioCaixaJPanel);
        } catch (InterruptedException ex) {
            Logger.getLogger(MenuView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_painelRelatorioCaixaJPanelMouseEntered

    private void painelRelatorioCaixaJPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelRelatorioCaixaJPanelMouseExited
        try {
            efeito.EfeitoIcone(backgroundRelatorioCaixaJLabel, painelRelatorioCaixaJPanel);
        } catch (InterruptedException ex) {
            Logger.getLogger(MenuView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_painelRelatorioCaixaJPanelMouseExited

    private void painelReceberContasJPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelReceberContasJPanelMouseEntered
        try {
            efeito.EfeitoIcone(backgroundReceberContasJLabel, painelReceberContasJPanel);
        } catch (InterruptedException ex) {
            Logger.getLogger(MenuView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_painelReceberContasJPanelMouseEntered

    private void painelReceberContasJPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelReceberContasJPanelMouseExited
        try {
            efeito.EfeitoIcone(backgroundReceberContasJLabel, painelReceberContasJPanel);
        } catch (InterruptedException ex) {
            Logger.getLogger(MenuView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_painelReceberContasJPanelMouseExited

    private void painelBuscarContaJPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelBuscarContaJPanelMouseEntered
        try {
            efeito.EfeitoIcone(backgroundBuscarContaJLabel, painelBuscarContaJPanel);
        } catch (InterruptedException ex) {
            Logger.getLogger(MenuView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_painelBuscarContaJPanelMouseEntered

    private void painelBuscarContaJPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelBuscarContaJPanelMouseExited
        try {
            efeito.EfeitoIcone(backgroundBuscarContaJLabel, painelBuscarContaJPanel);
        } catch (InterruptedException ex) {
            Logger.getLogger(MenuView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_painelBuscarContaJPanelMouseExited

    private void painelAddContaJPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelAddContaJPanelMouseEntered
        try {
            efeito.EfeitoIcone(backgroundAddContaJLabel, painelAddContaJPanel);
        } catch (InterruptedException ex) {
            Logger.getLogger(MenuView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_painelAddContaJPanelMouseEntered

    private void painelAddContaJPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelAddContaJPanelMouseExited
        try {
            efeito.EfeitoIcone(backgroundAddContaJLabel, painelAddContaJPanel);
        } catch (InterruptedException ex) {
            Logger.getLogger(MenuView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_painelAddContaJPanelMouseExited


    private void painelBuscarFuncionarioJPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelBuscarFuncionarioJPanelMouseEntered
        try {
            efeito.EfeitoIcone(backgroundBuscarFuncionarioJLabel, painelBuscarFuncionarioJPanel);
        } catch (InterruptedException ex) {
            Logger.getLogger(MenuView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_painelBuscarFuncionarioJPanelMouseEntered

    private void painelBuscarFuncionarioJPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelBuscarFuncionarioJPanelMouseExited
        try {
            efeito.EfeitoIcone(backgroundBuscarFuncionarioJLabel, painelBuscarFuncionarioJPanel);
        } catch (InterruptedException ex) {
            Logger.getLogger(MenuView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_painelBuscarFuncionarioJPanelMouseExited

    private void painelAddFuncionarioJPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelAddFuncionarioJPanelMouseEntered
        try {
            efeito.EfeitoIcone(backgroundAddFuncionarioJLabel, painelAddFuncionarioJPanel);
        } catch (InterruptedException ex) {
            Logger.getLogger(MenuView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_painelAddFuncionarioJPanelMouseEntered

    private void painelAddFuncionarioJPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelAddFuncionarioJPanelMouseExited
        try {
            efeito.EfeitoIcone(backgroundAddFuncionarioJLabel, painelAddFuncionarioJPanel);
        } catch (InterruptedException ex) {
            Logger.getLogger(MenuView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_painelAddFuncionarioJPanelMouseExited

    //PAINEL EXPANSIVO MENU

    private void vendasTextoJLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vendasTextoJLabelMouseClicked

        ExpandirMenu expandir = new ExpandirMenu(painelVendasJPanel, 3, painelBalcaoJPanel);
        expandir.DimencionarItem();
        expandir.RealocaMenu(painelCaixaJPanel, painelVendasJPanel.getHeight());
        expandir.RealocaMenu(painelContasPagarJPanel, painelVendasJPanel.getHeight() + painelCaixaJPanel.getHeight());
        expandir.RealocaMenu(painelFuncionarioJPanel, painelVendasJPanel.getHeight() + painelCaixaJPanel.getHeight() + painelContasPagarJPanel.getHeight());
        expandir.SetaIndicacao(indicadorVendasJLabel);

        if (expandir.ControllerBarraScroll(painelScrollMenuItemJScrollPane, painelCaixaJPanel.getHeight() + painelVendasJPanel.getHeight() + painelContasPagarJPanel.getHeight() + painelFuncionarioJPanel.getHeight()) == true) {
            painelBalcaoJPanel.setVisible(true);
            painelComandaJPanel.setVisible(true);
            painelMapaComandaJPanel.setVisible(true);
        } else {
            painelBalcaoJPanel.setVisible(false);
            painelComandaJPanel.setVisible(false);
            painelMapaComandaJPanel.setVisible(false);
        }

    }//GEN-LAST:event_vendasTextoJLabelMouseClicked

    private void vendasTextoJLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vendasTextoJLabelMouseEntered
        try {
            efeito.EfeitoNegrito(vendasTextoJLabel, vendasLinhaJLabel, 0);
            //vendasJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ItemVendasNegrito.png")));
        } catch (InterruptedException ex) {
            Logger.getLogger(MenuView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_vendasTextoJLabelMouseEntered

    private void vendasTextoJLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vendasTextoJLabelMouseExited
        try {
            efeito.EfeitoNegrito(vendasTextoJLabel, vendasLinhaJLabel, 1);
            //vendasJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ItemVendasNegrito.png")));
        } catch (InterruptedException ex) {
            Logger.getLogger(MenuView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_vendasTextoJLabelMouseExited

    private void caixaTextoJLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_caixaTextoJLabelMouseClicked

        int comparaExp;

        if (painelCaixaAbrirFecharJPanel.isVisible() == false) {

            painelCaixaJPanel.setSize(XMENU, 180);

            comparaExp = (painelBuscarContaJPanel.isVisible() == false) ? 27 : 127;
            painelContasPagarJPanel.setBounds(0, painelCaixaJPanel.getHeight() + painelVendasJPanel.getHeight(), XMENU, comparaExp);

            comparaExp = (painelBuscarFuncionarioJPanel.isVisible() == false) ? 27 : 127;
            painelFuncionarioJPanel.setBounds(0, painelCaixaJPanel.getHeight() + painelVendasJPanel.getHeight() + painelContasPagarJPanel.getHeight(), XMENU, comparaExp);

            try {
                Thread.sleep(1);
            } catch (InterruptedException ex) {
                Logger.getLogger(LoginView.class.getName()).log(Level.SEVERE, null, ex);
            }
            indicadorCaixaItemJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/SetaAberto.png"))); // NOI18N

            Dimension size = new Dimension(XMENU, painelCaixaJPanel.getHeight() + painelVendasJPanel.getHeight() + painelContasPagarJPanel.getHeight() + painelFuncionarioJPanel.getHeight());
            painelScrollMenuItemJScrollPane.setPreferredSize(size);

            painelCaixaAbrirFecharJPanel.setVisible(true);
            painelRelatorioCaixaJPanel.setVisible(true);
            painelReceberContasJPanel.setVisible(true);

        } else {

            painelCaixaAbrirFecharJPanel.setVisible(false);
            painelRelatorioCaixaJPanel.setVisible(false);
            painelReceberContasJPanel.setVisible(false);

            indicadorCaixaItemJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/SetaFechado.png"))); // NOI18N

            try {
                Thread.sleep(1);
            } catch (InterruptedException ex) {
                Logger.getLogger(LoginView.class.getName()).log(Level.SEVERE, null, ex);
            }

            painelCaixaJPanel.setSize(XMENU, painelExpansivoCaixaItemJPanel.getHeight());

            try {
                Thread.sleep(1);
            } catch (InterruptedException ex) {
                Logger.getLogger(LoginView.class.getName()).log(Level.SEVERE, null, ex);
            }

            comparaExp = (painelBuscarContaJPanel.isVisible() == false) ? 27 : 127;
            painelContasPagarJPanel.setBounds(0, painelCaixaJPanel.getHeight() + painelVendasJPanel.getHeight(), XMENU, comparaExp);

            comparaExp = (painelBuscarFuncionarioJPanel.isVisible() == false) ? 27 : 127;
            painelFuncionarioJPanel.setBounds(0, painelCaixaJPanel.getHeight() + painelVendasJPanel.getHeight() + painelContasPagarJPanel.getHeight(), XMENU, comparaExp);

            Dimension size = new Dimension(XMENU, painelCaixaJPanel.getHeight() + painelVendasJPanel.getHeight() + painelContasPagarJPanel.getHeight() + painelFuncionarioJPanel.getHeight());
            painelScrollMenuItemJScrollPane.setPreferredSize(size);

        }
    }//GEN-LAST:event_caixaTextoJLabelMouseClicked

    private void caixaTextoJLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_caixaTextoJLabelMouseEntered
        try {
            efeito.EfeitoNegrito(caixaTextoJLabel, caixaLinhaJLabel, 0);
            //vendasJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ItemVendasNegrito.png")));
        } catch (InterruptedException ex) {
            Logger.getLogger(MenuView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_caixaTextoJLabelMouseEntered

    private void caixaTextoJLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_caixaTextoJLabelMouseExited
        try {
            efeito.EfeitoNegrito(caixaTextoJLabel, caixaLinhaJLabel, 1);
            //vendasJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ItemVendasNegrito.png")));
        } catch (InterruptedException ex) {
            Logger.getLogger(MenuView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_caixaTextoJLabelMouseExited

    private void contasTextoJLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contasTextoJLabelMouseClicked

        ExpandirMenu expandir = new ExpandirMenu(painelContasPagarJPanel, 2, painelBuscarContaJPanel);
        expandir.DimencionarItem();
        expandir.RealocaMenu(painelFuncionarioJPanel, painelVendasJPanel.getHeight() + painelCaixaJPanel.getHeight() + painelContasPagarJPanel.getHeight());
        expandir.SetaIndicacao(indicadorContasPagarJLabel);

        if (expandir.ControllerBarraScroll(painelScrollMenuItemJScrollPane, painelCaixaJPanel.getHeight() + painelVendasJPanel.getHeight() + painelContasPagarJPanel.getHeight() + painelFuncionarioJPanel.getHeight()) == true) {
            painelBuscarContaJPanel.setVisible(true);
            painelAddContaJPanel.setVisible(true);

        } else {
            painelBuscarContaJPanel.setVisible(false);
            painelAddContaJPanel.setVisible(false);
        }
    }//GEN-LAST:event_contasTextoJLabelMouseClicked

    private void contasTextoJLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contasTextoJLabelMouseEntered
        try {
            efeito.EfeitoNegrito(contasTextoJLabel, contasLinhaJLabel, 0);
            //vendasJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ItemVendasNegrito.png")));
        } catch (InterruptedException ex) {
            Logger.getLogger(MenuView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_contasTextoJLabelMouseEntered

    private void contasTextoJLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contasTextoJLabelMouseExited
        try {
            efeito.EfeitoNegrito(contasTextoJLabel, contasLinhaJLabel, 1);
            //vendasJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ItemVendasNegrito.png")));
        } catch (InterruptedException ex) {
            Logger.getLogger(MenuView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_contasTextoJLabelMouseExited

    private void funcionarioTextoJLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_funcionarioTextoJLabelMouseClicked
        
        ExpandirMenu expandir = new ExpandirMenu(painelFuncionarioJPanel, 2, painelBuscarFuncionarioJPanel);
        expandir.DimencionarItem();
        expandir.SetaIndicacao(indicadorContasPagarJLabel);

        if (expandir.ControllerBarraScroll(painelScrollMenuItemJScrollPane, painelCaixaJPanel.getHeight() + painelVendasJPanel.getHeight() + painelContasPagarJPanel.getHeight() + painelFuncionarioJPanel.getHeight()) == true) {
            painelBuscarFuncionarioJPanel.setVisible(true);
            painelAddFuncionarioJPanel.setVisible(true);

        } else {
            painelBuscarFuncionarioJPanel.setVisible(false);
            painelAddFuncionarioJPanel.setVisible(false);
        }
    }//GEN-LAST:event_funcionarioTextoJLabelMouseClicked

    private void funcionarioTextoJLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_funcionarioTextoJLabelMouseEntered
        try {
            efeito.EfeitoNegrito(funcionarioTextoJLabel, funcionarioLinhaJLabel, 0);
            //vendasJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ItemVendasNegrito.png")));
        } catch (InterruptedException ex) {
            Logger.getLogger(MenuView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_funcionarioTextoJLabelMouseEntered

    private void funcionarioTextoJLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_funcionarioTextoJLabelMouseExited
        try {
            efeito.EfeitoNegrito(funcionarioTextoJLabel, funcionarioLinhaJLabel, 1);
            //vendasJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ItemVendasNegrito.png")));
        } catch (InterruptedException ex) {
            Logger.getLogger(MenuView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_funcionarioTextoJLabelMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MenuView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundAddContaJLabel;
    private javax.swing.JLabel backgroundAddFuncionarioJLabel;
    private javax.swing.JLabel backgroundBalcaoJLabel;
    private javax.swing.JLabel backgroundBuscarContaJLabel;
    private javax.swing.JLabel backgroundBuscarFuncionarioJLabel;
    private javax.swing.JLabel backgroundCaixaJLabel;
    private javax.swing.JLabel backgroundComandaJLabel;
    private javax.swing.JLabel backgroundMapaComandaJLabel;
    private javax.swing.JLabel backgroundReceberContasJLabel;
    private javax.swing.JLabel backgroundRelatorioCaixaJLabel;
    private javax.swing.JLabel caixaLinhaJLabel;
    private javax.swing.JLabel caixaTextoJLabel;
    private javax.swing.JLabel contasLinhaJLabel;
    private javax.swing.JLabel contasTextoJLabel;
    private javax.swing.JLabel funcionarioLinhaJLabel;
    private javax.swing.JLabel funcionarioTextoJLabel;
    private javax.swing.JLabel iconeAddConta;
    private javax.swing.JLabel iconeAddFuncionario;
    private javax.swing.JLabel iconeBalcao;
    private javax.swing.JLabel iconeBuscarContaJLabel;
    private javax.swing.JLabel iconeBuscarFuncionarioJLabel;
    private javax.swing.JLabel iconeCaixaAbrirFecharJLabel;
    private javax.swing.JLabel iconeComanda;
    private javax.swing.JLabel iconeMapaComanda;
    private javax.swing.JLabel iconeReceberConta;
    private javax.swing.JLabel iconeRelatorioCaixa;
    private javax.swing.JLabel indicadorCaixaItemJLabel;
    private javax.swing.JPanel indicadorCaixaItemJPanel;
    private javax.swing.JLabel indicadorContasPagarJLabel;
    private javax.swing.JPanel indicadorContasPagarJPanel;
    private javax.swing.JLabel indicadorFuncionarioJLabel;
    private javax.swing.JPanel indicadorFuncionarioJPanel;
    private javax.swing.JLabel indicadorVendasJLabel;
    private javax.swing.JPanel indicadorVendasJPanel;
    private javax.swing.JPanel menuItemJPanel;
    private javax.swing.JLabel menuItemJlabel;
    private javax.swing.JLabel menuJLabel;
    private javax.swing.JPanel menuJPanel;
    private javax.swing.JPanel painelAddContaJPanel;
    private javax.swing.JPanel painelAddFuncionarioJPanel;
    private javax.swing.JPanel painelBalcaoJPanel;
    private javax.swing.JPanel painelBuscarContaJPanel;
    private javax.swing.JPanel painelBuscarFuncionarioJPanel;
    private javax.swing.JPanel painelCaixaAbrirFecharJPanel;
    private javax.swing.JPanel painelCaixaJPanel;
    private javax.swing.JPanel painelComandaJPanel;
    private javax.swing.JPanel painelContasPagarJPanel;
    private javax.swing.JPanel painelExpansivoCaixaItemJPanel;
    private javax.swing.JPanel painelExpansivoContasPagarJPanel;
    private javax.swing.JPanel painelExpansivoFuncionarioJPanel;
    private javax.swing.JPanel painelExpansivoVendasJPanel;
    private javax.swing.JPanel painelFuncionarioJPanel;
    private javax.swing.JPanel painelMapaComandaJPanel;
    private javax.swing.JPanel painelMenuItemJPanel;
    private javax.swing.JPanel painelReceberContasJPanel;
    private javax.swing.JPanel painelRelatorioCaixaJPanel;
    private javax.swing.JPanel painelScrollMenuItemJScrollPane;
    private javax.swing.JPanel painelVendasJPanel;
    private javax.swing.JScrollPane scrollMenuItemJScrollPane;
    private javax.swing.JLabel textoAddContaJLabel;
    private javax.swing.JLabel textoAddFuncionarioJLabel;
    private javax.swing.JLabel textoBalcaoJLabel;
    private javax.swing.JLabel textoBuscarContaLabel;
    private javax.swing.JLabel textoBuscarFuncionarioLabel;
    private javax.swing.JLabel textoCaixaAbrirFecharJLabel;
    private javax.swing.JLabel textoComandaJLabel;
    private javax.swing.JLabel textoMapaComandaJLabel;
    private javax.swing.JLabel textoReceberContaJLabel;
    private javax.swing.JLabel textoRelatorioCaixaJLabel;
    private javax.swing.JLabel vendasLinhaJLabel;
    private javax.swing.JLabel vendasTextoJLabel;
    // End of variables declaration//GEN-END:variables
}
